-- ============================================================
-- PDFTV SUPABASE UPGRADE SCRIPT
-- Jalankan seluruh isi file ini di Supabase Dashboard > SQL Editor
-- Aman dijalankan berulang (idempotent).
-- ============================================================

-- ============================================================
-- 1. FIX ID COLLISION: jadikan id auto-generate (identity)
-- Insert baru TIDAK perlu mengirim id lagi; data lama tetap aman.
-- ============================================================
DO $$
BEGIN
    BEGIN
        ALTER TABLE public."PDFTV Feeds"
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION WHEN others THEN
        NULL; -- kolom id sudah menjadi identity, lewati
    END;
END $$;

-- ============================================================
-- 2. RPC UPTIME / KOMENTAR (atomic, anti race-condition)
-- ============================================================
CREATE OR REPLACE FUNCTION public.increment_upvote(p_id BIGINT, p_delta INT)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_count INT;
BEGIN
    IF p_delta NOT IN (1, -1) THEN
        RAISE EXCEPTION 'delta tidak valid';
    END IF;

    UPDATE public."PDFTV Feeds"
        SET upvotes = GREATEST(0, upvotes + p_delta)
        WHERE id = p_id
        RETURNING upvotes INTO new_count;

    IF new_count IS NULL THEN
        RAISE EXCEPTION 'postingan tidak ditemukan';
    END IF;

    RETURN new_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.append_comment(p_id BIGINT, p_text TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_comments JSONB;
    clean TEXT;
BEGIN
    clean := btrim(COALESCE(p_text, ''));
    IF clean = '' OR length(clean) > 300 THEN
        RAISE EXCEPTION 'komentar tidak valid (kosong / lebih dari 300 karakter)';
    END IF;

    UPDATE public."PDFTV Feeds"
        SET comments = comments || to_jsonb(clean::text)
        WHERE id = p_id
        RETURNING comments INTO new_comments;

    IF new_comments IS NULL THEN
        RAISE EXCEPTION 'postingan tidak ditemukan';
    END IF;

    RETURN new_comments;
END;
$$;

-- ============================================================
-- 3. RPC INSERT CONFESSION + rate limit sederhana per IP
-- (maks 1 postingan / 15 detik per IP)
-- ============================================================
ALTER TABLE public."PDFTV Feeds" ADD COLUMN IF NOT EXISTS poster_ip TEXT;

CREATE OR REPLACE FUNCTION public.insert_confession(
    p_alias TEXT,
    p_confession TEXT,
    p_gif_url TEXT DEFAULT NULL,
    p_is_nsfw BOOLEAN DEFAULT FALSE
)
RETURNS public."PDFTV Feeds"
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    clean_conf TEXT;
    clean_alias TEXT;
    clean_gif TEXT;
    client_ip TEXT;
    last_created TIMESTAMPTZ;
    new_row public."PDFTV Feeds";
BEGIN
    clean_conf := btrim(COALESCE(p_confession, ''));
    clean_alias := NULLIF(btrim(COALESCE(p_alias, '')), '');
    clean_gif := NULLIF(btrim(COALESCE(p_gif_url, '')), '');

    IF clean_conf = '' AND clean_gif IS NULL THEN
        RAISE EXCEPTION 'isi pengakuan atau link GIF terlebih dahulu';
    END IF;
    IF length(clean_conf) > 500 THEN
        RAISE EXCEPTION 'pengakuan maksimal 500 karakter';
    END IF;
    IF clean_gif IS NOT NULL AND clean_gif !~ '^https?://.+' THEN
        RAISE EXCEPTION 'link GIF harus dimulai dengan http(s)://';
    END IF;

    -- Rate limit per IP (abaikan jika header tidak tersedia, mis. dari SQL Editor)
    client_ip := COALESCE(
        split_part(COALESCE(current_setting('request.headers', true)::json->>'x-forwarded-for', ''), ',', 1),
        ''
    );
    IF client_ip <> '' THEN
        SELECT created_at INTO last_created
            FROM public."PDFTV Feeds"
            WHERE poster_ip = client_ip
            ORDER BY created_at DESC LIMIT 1;
        IF last_created IS NOT NULL AND last_created > NOW() - INTERVAL '15 seconds' THEN
            RAISE EXCEPTION 'terlalu cepat! tunggu sebentar sebelum posting lagi';
        END IF;
    END IF;

    INSERT INTO public."PDFTV Feeds" (alias, confession, gif_url, upvotes, comments, timestamp, is_pinned, is_nsfw, poster_ip)
    VALUES (
        COALESCE(clean_alias, 'Anonim'),
        clean_conf,
        clean_gif,
        0,
        '[]'::jsonb,
        (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
        FALSE,
        COALESCE(p_is_nsfw, FALSE),
        NULLIF(client_ip, '')
    )
    RETURNING * INTO new_row;

    RETURN new_row;
END;
$$;

-- ============================================================
-- 4. VERIFIKASI PASSWORD SERVER-SIDE (HASHED)
-- Password tidak lagi ada di kode client, dan tidak lagi
-- disimpan sebagai teks biasa di sini. Yang disimpan hanya hash
-- bcrypt, di schema `private` yang TIDAK diekspos PostgREST.
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS private.admin_credentials (
    role       TEXT PRIMARY KEY,
    pass_hash  TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
REVOKE ALL ON TABLE private.admin_credentials FROM anon, authenticated;

-- RLS aktif TANPA policy = tolak semua akses langsung dari anon/authenticated.
-- Tidak mengganggu verifikasi login, karena private.verify_credential adalah
-- SECURITY DEFINER dan berjalan sebagai pemilik tabel (pemilik melewati RLS).
-- Jangan pakai FORCE ROW LEVEL SECURITY — itu akan memblokir fungsinya juga.
ALTER TABLE private.admin_credentials ENABLE ROW LEVEL SECURITY;

-- Satu-satunya tempat password dibandingkan. SECURITY DEFINER agar
-- anon tetap bisa memverifikasi tanpa pernah bisa membaca tabelnya.
CREATE OR REPLACE FUNCTION private.verify_credential(p_role TEXT, p_pass TEXT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = private, public, extensions
AS $$
    SELECT EXISTS (
        SELECT 1 FROM private.admin_credentials
        WHERE role = p_role
          AND COALESCE(p_pass, '') <> ''
          AND pass_hash = crypt(p_pass, pass_hash)
    );
$$;

-- Setel / ganti password (jalankan manual di SQL Editor, bukan dari client):
--   SELECT private.set_credential('admin',     'PASSWORD_ADMIN_BARU');
--   SELECT private.set_credential('moderator', 'PASSWORD_MOD_BARU');
CREATE OR REPLACE FUNCTION private.set_credential(p_role TEXT, p_pass TEXT)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = private, extensions
AS $$
    INSERT INTO private.admin_credentials (role, pass_hash, updated_at)
    VALUES (p_role, crypt(p_pass, gen_salt('bf', 12)), now())
    ON CONFLICT (role) DO UPDATE
        SET pass_hash = EXCLUDED.pass_hash, updated_at = now();
$$;

CREATE OR REPLACE FUNCTION public.verify_moderator(p_pass TEXT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = private, public, extensions
AS $$
    SELECT private.verify_credential('moderator', p_pass);
$$;

CREATE OR REPLACE FUNCTION public.verify_admin(p_pass TEXT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = private, public, extensions
AS $$
    SELECT private.verify_credential('admin', p_pass);
$$;

-- ============================================================
-- 5. AKSI MODERATOR (pin / nsfw / hapus) via RPC
-- ============================================================
CREATE OR REPLACE FUNCTION public.moderator_update_feed(
    p_pass TEXT,
    p_id BIGINT,
    p_is_pinned BOOLEAN DEFAULT NULL,
    p_is_nsfw BOOLEAN DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.verify_moderator(p_pass) THEN
        RAISE EXCEPTION 'akses moderator ditolak';
    END IF;

    UPDATE public."PDFTV Feeds"
        SET is_pinned = COALESCE(p_is_pinned, is_pinned),
            is_nsfw   = COALESCE(p_is_nsfw, is_nsfw)
        WHERE id = p_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'postingan tidak ditemukan';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.moderator_delete_feed(p_pass TEXT, p_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.verify_moderator(p_pass) THEN
        RAISE EXCEPTION 'akses moderator ditolak';
    END IF;

    DELETE FROM public."PDFTV Feeds" WHERE id = p_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'postingan tidak ditemukan';
    END IF;
END;
$$;

-- ============================================================
-- 6. ADMIN: reset leaderboard via RPC
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_reset_leaderboard(p_pass TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.verify_admin(p_pass) THEN
        RAISE EXCEPTION 'akses admin ditolak';
    END IF;

    DELETE FROM public."PDFTV Blackjack Leaderboard";
END;
$$;

-- ============================================================
-- 7. PERKETAT RLS
-- Publik hanya boleh BACA. Semua penulisan (upvote, komentar,
-- posting, moderasi) kini hanya lewat RPC di atas.
-- Catatan: jalankan bagian ini TERAKHIR. Selama JS masih punya
-- fallback insert langsung, policy INSERT lama dipertahankan.
-- ============================================================
DROP POLICY IF EXISTS "Public Update Access" ON public."PDFTV Feeds";

-- Policy insert tetap ada sebagai fallback jika RPC belum tersedia.
-- (Opsional: hapus baris di bawah untuk memaksa semua insert lewat RPC)
-- DROP POLICY IF EXISTS "Public Insert Access" ON public."PDFTV Feeds";

-- Izin eksekusi RPC untuk publik
GRANT EXECUTE ON FUNCTION public.increment_upvote(BIGINT, INT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.append_comment(BIGINT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.insert_confession(TEXT, TEXT, TEXT, BOOLEAN) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_moderator(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_admin(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.moderator_update_feed(TEXT, BIGINT, BOOLEAN, BOOLEAN) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.moderator_delete_feed(TEXT, BIGINT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_reset_leaderboard(TEXT) TO anon, authenticated;

-- ============================================================
-- 8. SEED PASSWORD
-- Diset via hash, jadi tidak ada teks biasa yang disimpan di tabel.
-- Catatan: dua password ini sudah pernah publik di git history repo,
-- jadi sebaiknya diganti bila akses admin/moderator mau dibatasi.
-- Ganti kapan saja tanpa ubah kode:
--   SELECT private.set_credential('admin',     'PASSWORD_BARU');
--   SELECT private.set_credential('moderator', 'PASSWORD_BARU');
-- Cek hash terpasang (jangan bagikan nilai hash-nya):
--   SELECT role, updated_at FROM private.admin_credentials;
-- ============================================================
SELECT private.set_credential('admin',     'cikini123');
SELECT private.set_credential('moderator', 'rusdi123');
