-- ============================================================
-- PDFTV SUPABASE UPGRADE SCRIPT
-- Jalankan seluruh isi file ini di Supabase Dashboard > SQL Editor
-- Aman dijalankan berulang (idempotent).
-- ============================================================

-- ============================================================
-- 1. FIX ID COLLISION: jadikan id auto-generate (identity)
-- Insert baru TIDAK perlu mengirim id lagi; data lama tetap aman.
-- ============================================================
DO $$
BEGIN
    BEGIN
        ALTER TABLE public."PDFTV Feeds"
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION WHEN others THEN
        NULL; -- kolom id sudah menjadi identity, lewati
    END;
END $$;

-- ============================================================
-- 2. RPC UPTIME / KOMENTAR (atomic, anti race-condition)
-- ============================================================
CREATE OR REPLACE FUNCTION public.increment_upvote(p_id BIGINT, p_delta INT)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_count INT;
BEGIN
    IF p_delta NOT IN (1, -1) THEN
        RAISE EXCEPTION 'delta tidak valid';
    END IF;

    UPDATE public."PDFTV Feeds"
        SET upvotes = GREATEST(0, upvotes + p_delta)
        WHERE id = p_id
        RETURNING upvotes INTO new_count;

    IF new_count IS NULL THEN
        RAISE EXCEPTION 'postingan tidak ditemukan';
    END IF;

    RETURN new_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.append_comment(p_id BIGINT, p_text TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_comments JSONB;
    clean TEXT;
BEGIN
    clean := btrim(COALESCE(p_text, ''));
    IF clean = '' OR length(clean) > 300 THEN
        RAISE EXCEPTION 'komentar tidak valid (kosong / lebih dari 300 karakter)';
    END IF;

    UPDATE public."PDFTV Feeds"
        SET comments = comments || to_jsonb(clean::text)
        WHERE id = p_id
        RETURNING comments INTO new_comments;

    IF new_comments IS NULL THEN
        RAISE EXCEPTION 'postingan tidak ditemukan';
    END IF;

    RETURN new_comments;
END;
$$;

-- ============================================================
-- 3. RPC INSERT CONFESSION + rate limit sederhana per IP
-- (maks 1 postingan / 15 detik per IP)
-- ============================================================
-- pgcrypto dipakai untuk hash IP dan password (butuh digest/crypt).
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

ALTER TABLE public."PDFTV Feeds" ADD COLUMN IF NOT EXISTS poster_ip TEXT;

-- Penting: tabel lama mungkin belum punya created_at (CREATE TABLE IF NOT EXISTS
-- tidak menambah kolom ke tabel yang sudah ada), padahal rate limit memakainya.
ALTER TABLE public."PDFTV Feeds" ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- Isi created_at untuk baris lama dari timestamp (ms) agar pengurutan rate limit benar.
UPDATE public."PDFTV Feeds"
    SET created_at = to_timestamp(timestamp / 1000.0)
    WHERE created_at IS NULL AND timestamp IS NOT NULL;

-- Percepat query rate limit per IP (sebelumnya full scan).
CREATE INDEX IF NOT EXISTS idx_feeds_poster_ip
    ON public."PDFTV Feeds" (poster_ip, created_at DESC);

-- Konversi IP mentah yang sudah tersimpan menjadi hash (sekali jalan).
-- Skema pgcrypto diresolusi dinamis, jadi tetap jalan walau ekstensinya
-- tidak berada di schema `extensions`.
DO $$
DECLARE
    pgc_schema TEXT;
BEGIN
    SELECT n.nspname INTO pgc_schema
        FROM pg_extension e
        JOIN pg_namespace n ON n.oid = e.extnamespace
        WHERE e.extname = 'pgcrypto';

    IF pgc_schema IS NULL THEN
        RAISE NOTICE 'pgcrypto tidak ditemukan, lewati konversi IP lama';
        RETURN;
    END IF;

    EXECUTE format(
        'UPDATE public."PDFTV Feeds"
            SET poster_ip = encode(%I.digest(poster_ip || ''pdftv-feeds'', ''sha256''), ''hex'')
            WHERE poster_ip IS NOT NULL
              AND poster_ip <> ''''
              AND length(poster_ip) < 64',
        pgc_schema
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.insert_confession(
    p_alias TEXT,
    p_confession TEXT,
    p_gif_url TEXT DEFAULT NULL,
    p_is_nsfw BOOLEAN DEFAULT FALSE
)
RETURNS public."PDFTV Feeds"
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    clean_conf TEXT;
    clean_alias TEXT;
    clean_gif TEXT;
    client_ip TEXT;
    ip_hash TEXT;
    last_created TIMESTAMPTZ;
    new_row public."PDFTV Feeds";
BEGIN
    clean_conf := btrim(COALESCE(p_confession, ''));
    clean_alias := NULLIF(btrim(COALESCE(p_alias, '')), '');
    clean_gif := NULLIF(btrim(COALESCE(p_gif_url, '')), '');

    IF clean_conf = '' AND clean_gif IS NULL THEN
        RAISE EXCEPTION 'isi pengakuan atau link GIF terlebih dahulu';
    END IF;
    IF length(clean_conf) > 500 THEN
        RAISE EXCEPTION 'pengakuan maksimal 500 karakter';
    END IF;
    IF clean_gif IS NOT NULL AND clean_gif !~ '^https?://.+' THEN
        RAISE EXCEPTION 'link GIF harus dimulai dengan http(s)://';
    END IF;

    -- Rate limit per IP (abaikan jika header tidak tersedia, mis. dari SQL Editor).
    -- Yang disimpan HANYA hash IP, bukan IP mentah — postingan tetap anonim,
    -- tapi rate limit masih bisa bekerja.
    client_ip := COALESCE(
        split_part(COALESCE(current_setting('request.headers', true)::json->>'x-forwarded-for', ''), ',', 1),
        ''
    );
    IF client_ip <> '' THEN
        ip_hash := encode(digest(client_ip || 'pdftv-feeds', 'sha256'), 'hex');

        SELECT created_at INTO last_created
            FROM public."PDFTV Feeds"
            WHERE poster_ip = ip_hash
            ORDER BY created_at DESC LIMIT 1;
        IF last_created IS NOT NULL AND last_created > NOW() - INTERVAL '15 seconds' THEN
            RAISE EXCEPTION 'terlalu cepat! tunggu sebentar sebelum posting lagi';
        END IF;
    END IF;

    INSERT INTO public."PDFTV Feeds" (alias, confession, gif_url, upvotes, comments, timestamp, is_pinned, is_nsfw, poster_ip)
    VALUES (
        COALESCE(clean_alias, 'Anonim'),
        clean_conf,
        clean_gif,
        0,
        '[]'::jsonb,
        (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
        FALSE,
        COALESCE(p_is_nsfw, FALSE),
        ip_hash
    )
    RETURNING * INTO new_row;

    RETURN new_row;
END;
$$;

-- Retensi: hapus hash IP lama. Jalankan berkala (manual atau via pg_cron).
CREATE OR REPLACE FUNCTION public.purge_old_poster_ips(p_days INT DEFAULT 30)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    affected INTEGER;
BEGIN
    UPDATE public."PDFTV Feeds"
        SET poster_ip = NULL
        WHERE poster_ip IS NOT NULL
          AND created_at < NOW() - make_interval(days => GREATEST(COALESCE(p_days, 30), 1));
    GET DIAGNOSTICS affected = ROW_COUNT;
    RETURN affected;
END;
$$;

-- Fungsi perawatan: jangan diekspos ke publik.
REVOKE ALL ON FUNCTION public.purge_old_poster_ips(INT) FROM anon, authenticated;

-- ============================================================
-- 4. VERIFIKASI PASSWORD SERVER-SIDE (HASHED)
-- Password tidak lagi ada di kode client, dan tidak lagi
-- disimpan sebagai teks biasa di sini. Yang disimpan hanya hash
-- bcrypt, di schema `private` yang TIDAK diekspos PostgREST.
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS private.admin_credentials (
    role       TEXT PRIMARY KEY,
    pass_hash  TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
REVOKE ALL ON TABLE private.admin_credentials FROM anon, authenticated;

-- RLS aktif TANPA policy = tolak semua akses langsung dari anon/authenticated.
-- Tidak mengganggu verifikasi login, karena private.verify_credential adalah
-- SECURITY DEFINER dan berjalan sebagai pemilik tabel (pemilik melewati RLS).
-- Jangan pakai FORCE ROW LEVEL SECURITY — itu akan memblokir fungsinya juga.
ALTER TABLE private.admin_credentials ENABLE ROW LEVEL SECURITY;

-- Satu-satunya tempat password dibandingkan. SECURITY DEFINER agar
-- anon tetap bisa memverifikasi tanpa pernah bisa membaca tabelnya.
CREATE OR REPLACE FUNCTION private.verify_credential(p_role TEXT, p_pass TEXT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = private, public, extensions
AS $$
    SELECT EXISTS (
        SELECT 1 FROM private.admin_credentials
        WHERE role = p_role
          AND COALESCE(p_pass, '') <> ''
          AND pass_hash = crypt(p_pass, pass_hash)
    );
$$;

-- Setel / ganti password (jalankan manual di SQL Editor, bukan dari client):
--   SELECT private.set_credential('admin',     'PASSWORD_ADMIN_BARU');
--   SELECT private.set_credential('moderator', 'PASSWORD_MOD_BARU');
CREATE OR REPLACE FUNCTION private.set_credential(p_role TEXT, p_pass TEXT)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = private, extensions
AS $$
    INSERT INTO private.admin_credentials (role, pass_hash, updated_at)
    VALUES (p_role, crypt(p_pass, gen_salt('bf', 12)), now())
    ON CONFLICT (role) DO UPDATE
        SET pass_hash = EXCLUDED.pass_hash, updated_at = now();
$$;

CREATE OR REPLACE FUNCTION public.verify_moderator(p_pass TEXT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = private, public, extensions
AS $$
    SELECT private.verify_credential('moderator', p_pass);
$$;

CREATE OR REPLACE FUNCTION public.verify_admin(p_pass TEXT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = private, public, extensions
AS $$
    SELECT private.verify_credential('admin', p_pass);
$$;

-- ============================================================
-- 5. AKSI MODERATOR (pin / nsfw / hapus) via RPC
-- ============================================================
CREATE OR REPLACE FUNCTION public.moderator_update_feed(
    p_pass TEXT,
    p_id BIGINT,
    p_is_pinned BOOLEAN DEFAULT NULL,
    p_is_nsfw BOOLEAN DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.verify_moderator(p_pass) THEN
        RAISE EXCEPTION 'akses moderator ditolak';
    END IF;

    UPDATE public."PDFTV Feeds"
        SET is_pinned = COALESCE(p_is_pinned, is_pinned),
            is_nsfw   = COALESCE(p_is_nsfw, is_nsfw)
        WHERE id = p_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'postingan tidak ditemukan';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.moderator_delete_feed(p_pass TEXT, p_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.verify_moderator(p_pass) THEN
        RAISE EXCEPTION 'akses moderator ditolak';
    END IF;

    DELETE FROM public."PDFTV Feeds" WHERE id = p_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'postingan tidak ditemukan';
    END IF;
END;
$$;

-- ============================================================
-- 6. ADMIN: reset leaderboard via RPC
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_reset_leaderboard(p_pass TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.verify_admin(p_pass) THEN
        RAISE EXCEPTION 'akses admin ditolak';
    END IF;

    DELETE FROM public."PDFTV Blackjack Leaderboard";
END;
$$;

-- ============================================================
-- 7. LEADERBOARD: submit via RPC + RLS
-- Skor dihitung di browser, jadi anti-cheat sempurna tidak mungkin.
-- Yang bisa dilakukan server: menolak insert langsung, memvalidasi
-- rentang, dan membatasi spam per IP.
-- ============================================================
ALTER TABLE public."PDFTV Blackjack Leaderboard" ENABLE ROW LEVEL SECURITY;

-- Simpan hanya hash IP (bukan IP mentah) sebagai dasar rate limit.
ALTER TABLE public."PDFTV Blackjack Leaderboard"
    ADD COLUMN IF NOT EXISTS submit_ip TEXT;
ALTER TABLE public."PDFTV Blackjack Leaderboard"
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- Publik hanya boleh membaca. Tidak ada policy INSERT/UPDATE/DELETE,
-- sehingga penulisan langsung dari anon selalu ditolak.
DROP POLICY IF EXISTS "Public Insert Access" ON public."PDFTV Blackjack Leaderboard";
DROP POLICY IF EXISTS "Public Update Access" ON public."PDFTV Blackjack Leaderboard";
DROP POLICY IF EXISTS "Public Delete Access" ON public."PDFTV Blackjack Leaderboard";
DROP POLICY IF EXISTS "Public Read Access"   ON public."PDFTV Blackjack Leaderboard";
CREATE POLICY "Public Read Access" ON public."PDFTV Blackjack Leaderboard"
    FOR SELECT USING (true);

CREATE INDEX IF NOT EXISTS idx_blackjack_cash
    ON public."PDFTV Blackjack Leaderboard" (streak_count DESC);

CREATE INDEX IF NOT EXISTS idx_blackjack_submit_ip
    ON public."PDFTV Blackjack Leaderboard" (submit_ip, created_at DESC);

CREATE OR REPLACE FUNCTION public.submit_score(p_name TEXT, p_cash BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    clean_name  TEXT;
    client_ip   TEXT;
    last_submit TIMESTAMPTZ;
BEGIN
    clean_name := NULLIF(btrim(regexp_replace(COALESCE(p_name, ''), '[[:cntrl:]]', '', 'g')), '');

    IF clean_name IS NULL OR length(clean_name) > 12 THEN
        RAISE EXCEPTION 'nama tidak valid (1-12 karakter)';
    END IF;
    -- Batas bawah mengikuti syarat minimum di UI; batas atas menahan nilai mustahil.
    IF p_cash IS NULL OR p_cash < 500 OR p_cash > 1000000000 THEN
        RAISE EXCEPTION 'skor di luar rentang yang wajar';
    END IF;

    -- Rate limit per IP: maksimal 1 skor per menit.
    client_ip := COALESCE(
        split_part(COALESCE(current_setting('request.headers', true)::json->>'x-forwarded-for', ''), ',', 1),
        ''
    );
    IF client_ip <> '' THEN
        SELECT created_at INTO last_submit
            FROM public."PDFTV Blackjack Leaderboard"
            WHERE submit_ip = encode(digest(client_ip || 'pdftv-leaderboard', 'sha256'), 'hex')
            ORDER BY created_at DESC LIMIT 1;
        IF last_submit IS NOT NULL AND last_submit > NOW() - INTERVAL '60 seconds' THEN
            RAISE EXCEPTION 'terlalu cepat! tunggu sebentar sebelum mengirim skor lagi';
        END IF;
    END IF;

    INSERT INTO public."PDFTV Blackjack Leaderboard" (player_name, streak_count, submit_ip)
    VALUES (
        clean_name,
        p_cash,
        NULLIF(encode(digest(client_ip || 'pdftv-leaderboard', 'sha256'), 'hex'), '')
    );
END;
$$;

-- ============================================================
-- 8. PERKETAT RLS FEEDS
-- Publik hanya boleh BACA. Semua penulisan (upvote, komentar,
-- posting, moderasi) hanya lewat RPC di atas. JS sudah tidak punya
-- jalur tulis langsung, jadi policy insert lama ikut dicabut.
-- ============================================================
DROP POLICY IF EXISTS "Public Update Access" ON public."PDFTV Feeds";
DROP POLICY IF EXISTS "Public Insert Access" ON public."PDFTV Feeds";
DROP POLICY IF EXISTS "Public Delete Access" ON public."PDFTV Feeds";

-- Izin eksekusi RPC untuk publik
GRANT EXECUTE ON FUNCTION public.increment_upvote(BIGINT, INT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.append_comment(BIGINT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.insert_confession(TEXT, TEXT, TEXT, BOOLEAN) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_moderator(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_admin(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.moderator_update_feed(TEXT, BIGINT, BOOLEAN, BOOLEAN) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.moderator_delete_feed(TEXT, BIGINT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_reset_leaderboard(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_score(TEXT, BIGINT) TO anon, authenticated;

-- ============================================================
-- 9. PASSWORD ADMIN & MODERATOR (SETEL DI LUAR REPO)
-- Tidak ada password di file ini. Setel lewat SQL Editor memakai
-- cuplikan yang kamu simpan sendiri (lihat contoh di bawah), atau
-- file lokal yang tidak ikut ter-commit.
--
--   SELECT private.set_credential('admin',     '<password admin>');
--   SELECT private.set_credential('moderator', '<password moderator>');
--
-- Cek tanpa membuka hash-nya:
--   SELECT role, updated_at FROM private.admin_credentials;
--
-- Ganti kapan saja tanpa mengubah kode di website.
-- ============================================================
